backend/controllers/SpaceWorkController.php
<?php

namespace backend\controllers;

//use Codeception\Events;
use common\models\CategoriesToPlase;
use common\models\ConfRooms;
use common\models\Countryes;
use common\models\CustomFields;
use common\models\Favorites;
use Yii;
use common\models\SpaceWork;
use backend\models\search\SpaceWorkSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use common\models\Events;

/**
 * SpaceWorkController implements the CRUD actions for SpaceWork model.
 */
class SpaceWorkController extends BackendController
{
    /**
     * @inheritdoc
     */


    /**
     * Lists all SpaceWork models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SpaceWorkSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SpaceWork model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SpaceWork model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SpaceWork();

        $categories = ArrayHelper::map(CategoriesToPlase::find()->orderBy('category')->asArray()->all(), 'id', 'category');
        $countries = ArrayHelper::map(Countryes::find()->orderBy('country')->asArray()->all(), 'id', 'country');

        $SpacesData = Yii::$app->request->post('SpaceWork');
        if (!empty($SpacesData)) {
            //$SpacesData['created_at'] = date( 'Y-m-d', strtotime( $SpacesData['created_at'] ) );
            $model->attributes = $SpacesData;
            if ($model->validate() && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

        }
        return $this->render('create', [
            'model' => $model,
            'categories' => $categories,
            'countries' => $countries
        ]);
    }

    /**
     * Updates an existing SpaceWork model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $categories = ArrayHelper::map(CategoriesToPlase::find()->orderBy('category')->asArray()->all(), 'id', 'category');
        $countries = ArrayHelper::map(Countryes::find()->orderBy('country')->asArray()->all(), 'id', 'country');

        $SpacesData = Yii::$app->request->post('SpaceWork');
        if (!empty($SpacesData)) {
            //$SpacesData['created_at'] = date( 'Y-m-d', strtotime( $SpacesData['created_at'] ) );
            $model->attributes = $SpacesData;
            if ($model->validate() && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }

        }

        return $this->render('update', [
            'categories' => $categories,
            'countries' => $countries,
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing SpaceWork model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SpaceWork model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SpaceWork the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SpaceWork::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }


    public function actionConferenceView($space_id)
    {

        $query = ConfRooms::find()
            ->where(['space_id' => $space_id]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $space_model = $this->findModel($space_id);

        return $this->render('conference-list', [
            'dataProvider' => $dataProvider,
            'space_model' => $space_model,
        ]);
    }

    public function actionUpdateConference($id, $space_id)
    {

        $model = ConfRooms::findOne(['id' => $id, 'space_id' => $space_id]);

        if (!$model) {
            throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
        }

        $post = Yii::$app->request->post('ConfRooms');
        if ($post) {
            $post['space_id'] = $space_id;
            $model->attributes = $post;
            if ($model->validate() && $model->save()) {
                return $this->redirect(['conference-view', 'space_id' => $space_id]);
            } else {
                dd($model->errors);
            }
        }

        $space_model = $this->findModel($space_id);

        return $this->render('add-conf-room', [
            'model' => $model,
            'space_model' => $space_model,
        ]);
    }

    public function actionDeleteConference($id, $space_id)
    {
        $model = ConfRooms::findOne(['id' => $id, 'space_id' => $space_id]);

        if (!$model) {
            throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
        }

        $model->delete();

        return $this->redirect(['conference-view', 'space_id' => $space_id]);

    }

    public function actionAddConfRoom($space_id)
    {
        $model = new ConfRooms();
        $space_model = $this->findModel($space_id);
        $post = Yii::$app->request->post('ConfRooms');
        if ($post) {
            $post['space_id'] = $space_id;
            $model->attributes = $post;
            if ($model->validate() && $model->save()) {
                return $this->redirect(['conference-view', 'space_id' => $space_id]);
            } else {
                dd($model->errors);
            }


        }

        return $this->render('add-conf-room', [
            'model' => $model,
            'space_model' => $space_model,
        ]);
    }

    public function actionCustomFieldsList($space_id)
    {
        $query = CustomFields::find()
            ->where(['source_id' => $space_id])
            ->andWhere(['type_source' => Favorites::TYPE_PLACES]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $space_model = $this->findModel($space_id);

        return $this->render('custom-fields-list', [
            'dataProvider' => $dataProvider,
            'space_model' => $space_model,
        ]);
    }

    public function actionUpdateCustomField($id, $space_id)
    {
        $model = CustomFields::findOne(['id' => $id, 'source_id' => $space_id]);

        if (!$model) {
            throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
        }

        $post = Yii::$app->request->post('CustomFields');
        if ($post) {
            $post['source_id'] = $space_id;
            $model->attributes = $post;
            if ($model->validate() && $model->save()) {
                return $this->redirect(['custom-fields-list', 'space_id' => $space_id]);
            } else {
                dd($model->errors);
            }
        }

        $space_model = $this->findModel($space_id);

        return $this->render('add-custom-field', [
            'model' => $model,
            'space_model' => $space_model,
        ]);
    }

    public function actionAddCustomField($space_id)
    {
        $model = new CustomFields();

        $post = Yii::$app->request->post('CustomFields');
        if ($post) {
            $post['source_id'] = $space_id;
            $model->attributes = $post;
            $model->type_source = Favorites::TYPE_PLACES;
            if ($model->validate() && $model->save()) {
                return $this->redirect(['custom-fields-list', 'space_id' => $space_id]);
            } else {
                dd($model->errors);
            }
        }

        $space_model = $this->findModel($space_id);

        return $this->render('add-custom-field', [
            'model' => $model,
            'space_model' => $space_model,
        ]);

    }

    public function actionDeleteCustomField($id, $space_id)
    {
        CustomFields::findOne($id)->delete();
        return $this->redirect(['custom-fields-list', 'space_id' => $space_id]);
    }
}

backend/views/space-work/_form.php
<?php

use yii\helpers\Html;
use mihaildev\ckeditor\CKEditor;
use yii\bootstrap\ActiveForm;
use common\components\UploadImg\UploadImg;

/* @var $this yii\web\View */
/* @var $model common\models\SpaceWork */
/* @var $form yii\widgets\ActiveForm */

$this->registerCssFile('/plagins/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css');
$this->registerJsFile('/plagins/jquery.imgareaselect-0.9.10/js/jquery.imgareaselect.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('/js/crop_img.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$background_image = isset($model->image) ? $model->image : '';
?>

    <div class="space-work-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'id_cate_plase')->dropDownList($categories,
            ['class' => 'placeholder form-control',
                'prompt' => 'Choose from the list']) ?>

        <?= $form->field($model, 'id_country')->dropDownList($countries,
            ['class' => 'placeholder form-control',
                'prompt' => 'Select City'])->label('Select City') ?>

        <?= $form->field($model, 'title',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                    'maxlength' => true
            ]) ?>

        <? if (!$model->isNewRecord) {?>
            <div class="event_bg_image">
                <?php echo UploadImg::widget(
                    [
                        'imageName' => $background_image,
                        'pathToImg' => '/source/img/background_image/',
                        'action' => '/index.php?r=upload/upload-images',
                        'form_image_id' => 'background_image',
                        'place' => 'background_image',
                        'block_height' => 400,
                    ]
                );?>
            </div>
        <?php }else{?>
            <p>You can upload and crop image when space was created</p>
        <?php }?>

        <?= $form->field($model, 'description')->widget(CKEditor::className(), [
            'editorOptions' => [
                //'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                'inline' => false, //по умолчанию false
            ]
        ]) ?>

        <?= $form->field($model, 'text')->widget(CKEditor::className(), [
            'editorOptions' => [
                //'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                'inline' => false, //по умолчанию false
            ]
        ]) ?>

        <?= $form->field($model, 'address',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true
            ]) ?>

        <?= $form->field($model, 'email',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'email'
            ]) ?>

        <?= $form->field($model, 'phone',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'phone'
            ]) ?>

        <?= $form->field($model, 'square_meter',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>

        <?= $form->field($model, 'working_places',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>

        <?= $form->field($model, 'kitchen',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>

        <?= $form->field($model, 'max_spaces',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>

		<?= $form->field($model, 'max_office',['template'=>
												   "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
				 ->textInput([
								 'maxlength' => true, 'type' => 'number'
							 ]) ?>

        <?= $form->field($model, 'unfixiable_price',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>

        <?= $form->field($model, 'separate_price',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>

        <?= $form->field($model, 'one_day_price',['template'=>
            "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
            ->textInput([
                'maxlength' => true, 'type' => 'number'
            ]) ?>



        <input id="resource_id" type="hidden" value="<?=$model->id?>">
        <input id="resource_type" type="hidden" value="space">
        <div class="form-group">
            <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
        <br><br><br>

    </div>

backend/views/space-work/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\SpaceWorkSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="space-work-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_cate_plase') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'text') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'unfixiaed_price') ?>

    <?php // echo $form->field($model, 'separate_proce') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'background_image') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'square_meter') ?>

    <?php // echo $form->field($model, 'working_places') ?>

    <?php // echo $form->field($model, 'kitchen') ?>

    <?php // echo $form->field($model, 'conference_room') ?>

    <?php // echo $form->field($model, 'id_country') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/space-work/add-conf-room.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use mihaildev\ckeditor\CKEditor;
use yii\bootstrap\ActiveForm;
/**
 * Created by PhpStorm.
 * User: User
 * Date: 15.06.2018
 * Time: 11:45
 */
$this->title = Yii::t('backend', 'Add conference room')." to space: "." from Space: ".'<a href="'.Url::toRoute(['space-work/view', 'id' => $space_model->id]).'">'.$space_model->title.'</a>';
if($model->isNewRecord){
    $model->working_days = '1,2,3,4,5,6,7';
    $model->working_time_start = '09:00';
    $model->working_time_end= '21:00';
}
?>
<div class="wrap">
    <div class="space-work-form">
        <h1><?= $this->title ?></h1>
        <div class="form">
            <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($model, 'status')->dropDownList(
                [
                    0 =>'Not Active',
                    1 =>'Active',
                ]) ?>
            <?= $form->field($model, 'name',['template'=>
                "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
                ->textInput([
                    'maxlength' => true
                ]) ?>

            <?= $form->field($model, 'desc')->widget(CKEditor::className(), [
                'editorOptions' => [
                    //'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                    'inline' => false, //по умолчанию false
                ]
            ]) ?>
            <?= $form->field($model, 'price_for_hour',['template'=>
                "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
                ->textInput([
                    'maxlength' => true,'type'=>'number','step'=>'0.10'
                ]) ?>
            <?= $form->field($model, 'working_days',['template'=>
                "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
				->hiddenInput([
                    'maxlength' => true
                ]) ?>
            <?= $form->field($model, 'working_time_start',['template'=>
                "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
                ->textInput([
                    'maxlength' => true,'type'=>'time'
                ]) ?>
            <?= $form->field($model, 'working_time_end',['template'=>
                "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
                ->textInput([
                    'maxlength' => true,'type'=>'time'
                ]) ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
            <br><br><br>
        </div>
    </div>
</div>

backend/views/space-work/add-custom-field.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use mihaildev\ckeditor\CKEditor;
use yii\bootstrap\ActiveForm;
/**
 * Created by PhpStorm.
 * User: User
 * Date: 15.06.2018
 * Time: 11:45
 */

if(!$model->isNewRecord){
    $prefix = 'Update';
}else{
    $prefix = 'Add';
}
$this->title = Yii::t('backend', $prefix.' custom field')." to space: ".'<a href="'.Url::toRoute(['space-work/view', 'id' => $space_model->id]).'">'.$space_model->title.'</a>';
?>
<div class="wrap">
    <div class="space-work-form">
        <h1><?= $this->title ?></h1>
        <div class="form">
            <?php $form = ActiveForm::begin(); ?>
            <?= $form->field($model, 'title_field',['template'=>
                "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
                ->textInput([
                    'maxlength' => true
                ]) ?>

            <?= $form->field($model, 'description_field')->widget(CKEditor::className(), [
                'editorOptions' => [
                    //'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                    'inline' => false, //по умолчанию false
                ]
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
            <br><br><br>
        </div>
    </div>
</div>

backend/views/space-work/conference-list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\SpaceWorkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Conference list')." from Space: ".$space_model->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wrap">
    <div class="conference-index">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a(Yii::t('backend', 'Add conference room'), ['add-conf-room','space_id'=>$space_model->id], ['class' => 'btn btn-success']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                //'id',
                [
                    'attribute' => 'status',
                    'content' => function ($data) {
                        $status_mass = [
                            0 =>'Not Active',
                            1 =>'Active',
                        ];
                        return $status_mass[$data->status];
                    },
                ],
                [
                    'attribute' => 'name',
                    'content' => function ($data) {
                        return $data->name;
                    },
                    'options'=>['style'=>'width:200px;'],
                ],

                [
                    'attribute' => 'desc',
                    'content' => function ($data) {
                        return $data->desc;
                    },
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'options'=>['style'=>'width:200px'],
                    //'controller' => 'properties',
                    'template' => '{update}&nbsp;&nbsp;&nbsp;{delete}&nbsp;&nbsp;&nbsp;{report}',
                    'buttons' => [
                        'update' => function ($url,$data) {
                            return '<a href="'.Url::toRoute(['update-conference', 'id' => $data->id,'space_id'=>$data->space_id]).'"><span class="glyphicon glyphicon-pencil"></span></a>';
                        },
                        'delete' => function ($url,$data) {
                            return '<a href="'.Url::toRoute(['delete-conference', 'id' => $data->id,'space_id'=>$data->space_id]).'"><span class="glyphicon glyphicon-trash"></span></a>';
                        },
                    ],
                ],
            ],
        ]); ?>
    </div>
</div>

backend/views/space-work/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\SpaceWork */

$this->title = Yii::t('backend', 'Create Space Work');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Space Works'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="space-work-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories,
        'countries' => $countries
    ]) ?>

</div>

backend/views/space-work/custom-fields-list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\SpaceWorkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Custom fields list')." from Space: ".'<a href="'.Url::toRoute(['space-work/view', 'id' => $space_model->id]).'">'.$space_model->title.'</a>';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wrap">
    <div class="conference-index">
        <h1><?= $this->title ?></h1>

        <p>
            <?= Html::a(Yii::t('backend', 'Add custom field'), ['add-custom-field','space_id'=>$space_model->id], ['class' => 'btn btn-success']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'title_field',
                'description_field:html',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'options'=>['style'=>'width:200px'],
                    //'controller' => 'properties',
                    'template' => '{update}&nbsp;&nbsp;&nbsp;{delete}&nbsp;&nbsp;&nbsp;{report}',
                    'buttons' => [
                        'update' => function ($url,$data) {
                            return '<a href="'.Url::toRoute(['update-custom-field', 'id' => $data->id,'space_id'=>$data->source_id]).'"><span class="glyphicon glyphicon-pencil"></span></a>';
                        },
                        'delete' => function ($url,$data) {
                            return '<a href="'.Url::toRoute(['delete-custom-field', 'id' => $data->id,'space_id'=>$data->source_id]).'"><span class="glyphicon glyphicon-trash"></span></a>';
                        },
                    ],
                ],
            ],
        ]); ?>
    </div>
</div>

backend/views/space-work/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\SpaceWorkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Space Works');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="space-work-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('backend', 'Add Space'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'image',
                'contentOptions' => function ($model, $key, $index, $column) {
                    return ['class' => 'id-img'];
                },
                'content' => function ($data) {
                    $dir = Yii::getAlias("@background_image");
                    return Html::img(Yii::$app->params['front-url'].$dir."/icon/".$data->image,['width'=>100]);
                }
            ],
            [
                'attribute' => 'id_cate_plase',
                'label' => 'Category',
                'content' => function ($data) {
                    return $data->catePlase->category;
                }
            ],
            [
                'attribute' => 'title',
                'label' => 'Title',
                'content' => function ($data) {
                    return $data->title;
                }
            ],
            [
                'attribute' => 'description',
                'content' => function ($data) {
                    return \yii\helpers\StringHelper::truncate(strip_tags($data->description), 200);
                }
            ],
            [
                'attribute' => 'text',
                'content' => function ($data) {
                    return \yii\helpers\StringHelper::truncate(strip_tags($data->text), 200);
                }
            ],
            //'email:email',
            //'unfixiaed_price',
            //'separate_proce',
            //'address',
            //'phone',
            //'background_image',
            //'image',
            //'square_meter',
            //'working_places',
            //'kitchen',
            //'conference_room',
            //'id_country',
            //'created_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:110px'],
                //'controller' => 'properties',
                'template' => '{view}&nbsp;&nbsp;&nbsp;{update}&nbsp;&nbsp;&nbsp;{delete}&nbsp;&nbsp;&nbsp;{report}',
            ],
        ],
    ]); ?>
</div>

backend/views/space-work/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\SpaceWork */

$this->title = Yii::t('backend', 'Update Space Work: {nameAttribute}', [
    'nameAttribute' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Space Works'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="space-work-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories,
		'countries' => $countries
    ]) ?>

</div>