backend/controllers/EventsController.php
<?php

	namespace backend\controllers;

	use common\models\CategoriesTypeEvent;
    use common\models\LecturesAssnSpeakers;
    use common\models\UserProfile;
	use yii\data\ActiveDataProvider;
	use common\models\Countryes;
	use common\models\CustomFields;
	use common\models\Favorites;
	use common\models\Lectures;
	use common\models\PartnerEvents;
	use common\models\Partners;
	use common\models\Speakers;
	use Yii;
	use common\models\Events;
	use backend\models\search\EventsSearch;
	use yii\db\Query;
	use yii\helpers\Url;
	use yii\web\Controller;
	use yii\web\NotFoundHttpException;
	use yii\filters\VerbFilter;
	use yii\helpers\ArrayHelper;

	/**
	 * EventsController implements the CRUD actions for Events model.
	 */
	class EventsController extends BackendController
	{
		/**
		 * @inheritdoc
		 */


		/**
		 * Lists all Events models.
		 * @return mixed
		 */
		public function actionIndex()
		{
			$searchModel  = new EventsSearch();
			$dataProvider = $searchModel -> search( Yii ::$app -> request -> queryParams );

			return $this -> render(
				'index',
				[
					'searchModel'  => $searchModel,
					'dataProvider' => $dataProvider,
				]
			);
		}

		/**
		 * Displays a single Events model.
		 *
		 * @param integer $id
		 *
		 * @return mixed
		 * @throws NotFoundHttpException if the model cannot be found
		 */
		public function actionView( $id )
		{
			return $this -> render(
				'view',
				[
					'model'             => $this -> findModel( $id ),
				]
			);
		}

//		public function actionAddField()
//		{
//			$model = new CustomFields();
//			if( Yii ::$app -> request -> isAjax )
//			{
//				$status             = TRUE;
//				$getOptionsPostData = Yii ::$app -> request -> post();
//				if( !empty( $getOptionsPostData[ 'titleField' ] ) && !empty( $getOptionsPostData[ 'descField' ] ) )
//				{
//					$model -> title_field       = $getOptionsPostData[ 'titleField' ];
//					$model -> description_field = $getOptionsPostData[ 'descField' ];
//					$model -> source_id         = $getOptionsPostData[ 'source_id' ];
//					$model -> type_source       = $getOptionsPostData[ 'type_source' ];
//					if( $model -> validate() )
//					{
//						$model -> save();
//					}
//				}
//				else
//				{
//					Yii ::$app -> session -> setFlash( 'message', 'No fields are filled' );
//					return $this -> redirect( Url ::toRoute( [ 'view', 'add_option' => 'add_field', 'id' => $getOptionsPostData[ 'source_id' ] ] ) );
//				}
//				$getLastAddField = CustomFields ::find() -> orderBy( [ 'id' => SORT_DESC ] ) -> all();
//				$title           = $getLastAddField[ 0 ] -> title_field;
//				$deck            = $getLastAddField[ 0 ] -> description_field;
//				$id_field        = $getLastAddField[ 0 ] -> id;
//				return json_encode(
//					[
//						'id_field' => $id_field,
//						'status'   => $status,
//						'title'    => $title,
//						'deck'     => $deck,
//					]
//				);
//			}
//			return $status = FALSE;
//		}

		/*public function actionAddPartner()
		{
			$model = new PartnerEvents();
			if( Yii ::$app -> request -> isAjax )
			{
				$status             = TRUE;
				$getOptionsPostData = Yii ::$app -> request -> post();
				if( !empty( $getOptionsPostData ) )
				{
					$model -> id_event   = $getOptionsPostData[ 'id_event' ];
					$model -> id_partner = $getOptionsPostData[ 'select_partner' ];
					if( !$model -> save() )
					{
						dd( $model -> errors );
					}
				}
				$getLastAddPartner = PartnerEvents ::getLastAddPartner( $getOptionsPostData[ 'id_event' ] );
				$logo              = $getLastAddPartner[ 'partners' ] -> logo_partner;
				$title             = $getLastAddPartner[ 'partners' ] -> title_partner;
				$id_partner        = $getLastAddPartner -> id_partner;
				return json_encode(
					[
						'status'     => $status,
						'title'      => $title,
						'logo'       => $logo,
						'id_partner' => $id_partner,
					]
				);
			}
			return $status = FALSE;
		}*/

//		public function actionSetTypeEvent()
//		{
//			$getData = Yii ::$app -> request -> post();
//			$id      = $getData[ 'id_event_in_select' ];
//			if( Yii ::$app -> request -> isAjax )
//			{
//				$model               = Events ::findOne( $id );
//				$model -> scenario   = Events::SCENARIO_UPDATE_TYPE_EVENT;
//				$model -> type_event = $getData[ 'type_event' ];
//				if( $model -> save() )
//				{
//					return $this -> redirect( [ 'view', 'id' => $id ] );
//				}
//			}
//		}

//		public function actionAddLectures()
//		{
//			$model = new Lectures();
//			if( Yii ::$app -> request -> isAjax )
//			{
//				$status             = TRUE;
//				$getOptionsPostData = Yii ::$app -> request -> post();
//				if( !empty( $getOptionsPostData[ 'subject' ] ) && !empty( $getOptionsPostData[ 'time_from' ] ) && !empty( $getOptionsPostData[ 'time_to' ] ) && !empty( $getOptionsPostData[ 'speaker_id' ] ) )
//				{
//					$model -> id_event   = $getOptionsPostData[ 'id_event' ];
//					$model -> time_from  = $getOptionsPostData[ 'time_from' ];
//					$model -> time_to    = $getOptionsPostData[ 'time_to' ];
//					$model -> subject    = $getOptionsPostData[ 'subject' ];
//					$model -> speaker_id = $getOptionsPostData[ 'speaker_id' ];
//					if( $getOptionsPostData[ 'numberForAdditionSpeaker' ] == 1 && !empty( $getOptionsPostData[ 'additional_speaker_id' ] ) )
//					{
//						$model -> additional_speaker_id = $getOptionsPostData[ 'additional_speaker_id' ];
//					}
//					if( $model -> validate() )
//					{
//						$model -> save();
//					}
//					else
//					{
//						dd( $model -> errors );
//					}
//				}
//				else
//				{
//					Yii ::$app -> session -> setFlash( 'message', 'No fields are filled' );
//					return $this -> redirect( Url ::toRoute( [ 'view', 'add_option' => 'add_lectures', 'id' => $getOptionsPostData[ 'id_event' ] ] ) );
//				}
//				$getLastAddLecture = Lectures ::getLastLecture( $getOptionsPostData[ 'numberForAdditionSpeaker' ] );
//				$time_from         = $getLastAddLecture[ 'time_from' ];
//				$time_to           = $getLastAddLecture[ 'time_to' ];
//				$subject           = $getLastAddLecture[ 'subject' ];
//
//				$speaker_name       = $getLastAddLecture[ 'speaker_name' ];
//				$speaker_avatar     = $getLastAddLecture[ 'speaker_avatar' ];
//				$speaker_positional = $getLastAddLecture[ 'speaker_positional' ];
//
//				$id_lecture = $getLastAddLecture[ 'id_lecture' ];
//				if( $getOptionsPostData[ 'numberForAdditionSpeaker' ] == 0 && empty( $getOptionsPostData[ 'additional_speaker_id' ] ) )
//				{
//					return json_encode(
//						[
//							'status'    => $status,
//							'time_from' => $time_from,
//							'time_to'   => $time_to,
//							'subject'   => $subject,
//
//							'speaker_name'       => $speaker_name,
//							'speaker_avatar'     => $speaker_avatar,
//							'speaker_positional' => $speaker_positional,
//							'getOptionsPostData' => $getOptionsPostData[ 'numberForAdditionSpeaker' ],
//
//							'id_lecture' => $id_lecture,
//						]
//					);
//				}
//				else
//				{
//					$additional_speaker_name     = $getLastAddLecture[ 'additional_speaker_name' ];
//					$additional_speaker_avatar   = $getLastAddLecture[ 'additional_speaker_avatar' ];
//					$additional_speaker_position = $getLastAddLecture[ 'additional_speaker_position' ];
//					$additional_speaker_id       = $getLastAddLecture[ 'additional_speaker_id' ];
//					return json_encode(
//						[
//							'status'    => $status,
//							'time_from' => $time_from,
//							'time_to'   => $time_to,
//							'subject'   => $subject,
//
//							'speaker_name'       => $speaker_name,
//							'speaker_avatar'     => $speaker_avatar,
//							'speaker_positional' => $speaker_positional,
//
//							'additional_speaker_name'     => $additional_speaker_name,
//							'additional_speaker_avatar'   => $additional_speaker_avatar,
//							'additional_speaker_position' => $additional_speaker_position,
//							'getOptionsPostData'          => $getOptionsPostData[ 'numberForAdditionSpeaker' ],
//
//							'id_lecture'            => $id_lecture,
//							'additional_speaker_id' => $additional_speaker_id,
//						]
//					);
//				}
//			}
//			return $status = FALSE;
//		}

		/**
		 * Creates a new Events model.
		 * If creation is successful, the browser will be redirected to the 'view' page.
		 * @return mixed
		 */
		public function actionCreate()
		{
			$model = new Events();

			$categories = ArrayHelper ::map( CategoriesTypeEvent ::find() -> orderBy( 'category' ) -> asArray() -> all(), 'id', 'category' );
			$country    = ArrayHelper ::map( Countryes ::find() -> orderBy( 'country' ) -> asArray() -> all(), 'id', 'country' );
			$EventsData = Yii ::$app -> request -> post( 'Events' );
			if( !empty( $EventsData ) )
			{
				$EventsData[ 'date_event' ] = date( 'Y-m-d', strtotime( $EventsData[ 'date_event' ] ) );
				$model -> attributes        = $EventsData;
				if( $model -> validate() && $model -> save() )
				{
					return $this -> redirect( [ 'view', 'id' => $model -> id ] );
				}
			}
			return $this -> render(
				'create',
				[
					'model'      => $model,
					'categories' => $categories,
					'country'    => $country,
				]
			);
		}

		/**
		 * Updates an existing Events model.
		 * If update is successful, the browser will be redirected to the 'view' page.
		 *
		 * @param integer $id
		 *
		 * @return mixed
		 * @throws NotFoundHttpException if the model cannot be found
		 */
		public function actionUpdate( $id )
		{
			$model = $this -> findModel( $id );

			$EventsData = Yii ::$app -> request -> post( 'Events' );
			$categories = ArrayHelper ::map( CategoriesTypeEvent ::find() -> orderBy( 'category' ) -> asArray() -> all(), 'id', 'category' );
			$country    = ArrayHelper ::map( Countryes ::find() -> orderBy( 'country' ) -> asArray() -> all(), 'id', 'country' );
			if( !empty( $EventsData ) )
			{
				$EventsData[ 'date_event' ] = date( 'Y-m-d', strtotime( $EventsData[ 'date_event' ] ) );
				$model -> attributes        = $EventsData;

backend/views/events/_form.php
<?php

use yii\helpers\Html;
use mihaildev\ckeditor\CKEditor;
use yii\bootstrap\ActiveForm;
use common\components\UploadImg\UploadImg;

/* @var $this yii\web\View */
/* @var $model common\models\Events */
/* @var $form yii\widgets\ActiveForm */
$this->registerJs(
    "$('#datepicker input').datepicker({                    
        format: 'mm/dd/yyyy',
        orientation: 'bottom left',
        inline: false,
        sideBySide: false,
        showWeekDays: false 
    });",
    \yii\web\View::POS_READY
);
$this->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css');
$this->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.css');
$this->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerCssFile('/plagins/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css');
$this->registerJsFile('/plagins/jquery.imgareaselect-0.9.10/js/jquery.imgareaselect.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('/js/crop_img.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$background_image = isset($model->image) ? $model->image : '';
?>

<div class="events-form adminpanel_form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_cate_event')->dropDownList($categories,
        ['class' => 'placeholder form-control',
            'prompt' => 'Choose from the list',
        ]) ?>
    <?= $form->field($model, 'id_country')->dropDownList($country,
        ['class' => 'placeholder form-control',
            'prompt' => 'Select Country',
        ]) ?>

    <?= $form->field($model, 'type_event') -> dropDownList(
        [
            3 => 'Weekly',
            1 => 'Single-time',
        ],
        ['id' => 'check_select' ]
    );
    ?>
    <?= $form->field($model, 'title',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>

    <? if (!$model->isNewRecord) {?>
        <div class="event_bg_image">
                <?php echo UploadImg::widget(
                    [
                        'imageName' => $background_image,
                        'pathToImg' => '/source/img/background_image/',
                        'action' => '/index.php?r=upload/upload-images',
                        'form_image_id' => 'background_image',
                        'place' => 'background_image',
                        'block_height' => 400,
                    ]
                );?>
        </div>
    <?php }else{?>
        <p>You can upload and crop image when events was created</p>
    <?php }?>


    <?= $form->field($model, 'description')->widget(CKEditor::className(), [
        'editorOptions' => [
            //'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
            'inline' => false, //по умолчанию false
        ]
    ]) ?>
    <?= $form->field($model, 'text')->widget(CKEditor::className(), [
        'editorOptions' => [
            //'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
            'inline' => false, //по умолчанию false
        ]
    ]) ?>

    <?= $form->field($model, 'price_ticket_event',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>
    <div id="datepicker">
    <?= $form->field($model, 'date_event',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>
    </div>

    <?= $form->field($model, 'time_start_event',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'type' => 'time'
        ]) ?>

    <?= $form->field($model, 'time_end_event',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'type' => 'time'
        ]) ?>

    <?= $form->field($model, 'address',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>

    <?= $form->field($model, 'max_spaces',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>

    <?= $form->field($model, 'phone',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>

    <?= $form->field($model, 'email',['template'=>
        "<div class=\"form-control\">\n
                                {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                            </div>"])
        ->textInput([
            'autocomplete'=>'off', 'autofocus' => true, 'maxlength' => true
        ]) ?>
    <input id="resource_id" type="hidden" value="<?=$model->id?>">
    <input id="resource_type" type="hidden" value="event">
    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<script>
    //window.CKEDITOR_BASEPATH="/assets/3f6c234c/"
</script>

backend/views/events/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\EventsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_cate_event') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'text') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'price_ticket_event') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'background_image') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'time_start_event') ?>

    <?php // echo $form->field($model, 'time_end_event') ?>

    <?php // echo $form->field($model, 'date_event') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/events/add-fields.php
<?php
	use yii\helpers\Html;
    use mihaildev\ckeditor\CKEditor;
	use yii\helpers\Url;
	use yii\bootstrap\ActiveForm;

	if(!$model->isNewRecord){
		$prefix = 'Update';
	}else{
		$prefix = 'Add';
	}
	$this->title = Yii::t('backend', $prefix.' field')." to event: ".'<a href="'.Url::toRoute(['events/view', 'id' => $event_model->id]).'">'.$event_model->title.'</a>';

	$event_id = Yii ::$app -> request -> get('event_id');
?>
<div class="wrap">
	<div class="space-work-form">
		<h1><?= $this->title ?></h1>
		<div class="form">
			<?php $form = ActiveForm::begin(); ?>
			<?= $form->field($model, 'title_field',['template'=>
														  "<div class=\"form-control\">\n
                                    {input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
                                </div>"])
					 ->textInput([
									 'maxlength' => true
								 ]) ?>
            <?= $form->field($model, 'description_field')->widget(CKEditor::className(), [
                'editorOptions' => [
                    //'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                    'inline' => false, //по умолчанию false
                ]
            ]) ?>
			<input type="hidden" name="CustomFields[source_id]" value="<?= $event_id ?>">
			<input type="hidden" name="CustomFields[type_source]" value="<?= \common\models\Favorites::TYPE_EVENTS ?>">
			<div class="form-group">
				<?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
			</div>

			<?php ActiveForm::end(); ?>
			<br><br><br>
		</div>
	</div>
</div>

backend/views/events/add-lecture.php
<?php
	use yii\helpers\Html;
	use yii\helpers\Url;
    use kartik\select2\Select2;
	use yii\bootstrap\ActiveForm;

	if(!$model->isNewRecord){
		$prefix = 'Update';
	}else{
		$prefix = 'Add';
	}
	$this->title = Yii::t('backend', $prefix.'Lecture')." to event: ".'<a href="'.Url::toRoute(['events/view', 'id' => $event_model->id]).'">'.$event_model->title.'</a>';

	$event_id = Yii ::$app -> request -> get('event_id');
?>
<div class="wrap">
	<div class="space-work-form">
		<h1><?= $this->title ?></h1>
		<div class="form">
			<?php $form = ActiveForm ::begin(); ?>
			<br>
			<?= $form->field($model, 'time_from',['template'=>
															   "<div class=\"form-control\">\n
											{input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
										</div>"])
					 ->textInput([
									 'type' => 'time'
								 ]) ?>

			<?= $form->field($model, 'time_to',['template'=>
															 "<div class=\"form-control\">\n
											{input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
										</div>"])
					 ->textInput([
									 'type' => 'time'
								 ]) ?>

			<?= $form->field($model, 'subject',['template'=>
															 "<div class=\"form-control\">\n
											{input}{beginLabel}{labelTitle}{endLabel}\n{error}\n{hint}\n
										</div>"])
					 ->textInput([
									 'autocomplete'=>'off', 'autofocus' => true
								 ]) ?>

            <?php

            echo $form->field($model, 'speaker_ids')->widget(Select2::className(),[
                'data' => $getAndSetSpeakers,
                'options' => [
                    'placeholder' => 'Please select speakers * ',
                    'multiple' => true,
                    'class' => 'form-control',
                    'id' => 'speakers-select',
                ],
            ])->label(false);
            ?>
			<?= Html ::submitButton( Yii ::t( 'backend', $prefix ), [ 'class' => 'btn btn-success', 'id' => 'add_lecture_data' ] ) ?>
			<?php ActiveForm ::end() ?>
		</div>
	</div>
</div>

backend/views/events/add-partner.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
/**
 * Created by PhpStorm.
 * User: User
 * Date: 15.06.2018
 * Time: 11:45
 */

if(!$model->isNewRecord){
    $prefix = 'Update';
}else{
    $prefix = 'Add';
}
$event_id = Yii ::$app -> request -> get('event_id');
$this->title = Yii::t('backend', $prefix.' partner')." to event: ".'<a href="'.Url::toRoute(['events/view', 'id' => $event_model->id]).'">'.$event_model->title.'</a>';
?>
<div class="wrap">
    <div class="space-work-form">
        <h1><?= $this->title ?></h1>
        <div class="form">
            <?php $form = ActiveForm::begin(); ?>

				<?= $form -> field( $model, 'id_partner' ) -> dropDownList(
					$getAllPartner,
					[ 'class'  => 'placeholder form-control',
					  'prompt' => 'Select speaker',
					]
				) ?>
	        <input type="hidden" value="<?= $event_id  ?>" name="PartnerEvents[event_id]">
            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
            <br><br><br>
        </div>
    </div>
</div>

backend/views/events/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Events */

$this->title = Yii::t('backend', 'Create Events');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Events'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories,
        'country' => $country,
    ]) ?>

</div>

backend/views/events/partners-list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\SpaceWorkSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$event_id = $event_model->id;
$this->title = Yii::t('backend', 'Partners list')." from Event: ".'<a href="'.Url::toRoute(['events/view', 'id' => $event_id]).'">'.$event_model->title.'</a>';
$this->params['breadcrumbs'][] = $this->title;
$dir = Yii::getAlias("@logo");

?>
<div class="wrap">
    <div class="conference-index">
        <h1><?= $this->title ?></h1>

        <p>
            <?= Html::a(Yii::t('backend', 'Add partner'), ['add-partner','event_id'=>$event_id], ['class' => 'btn btn-success']) ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'title_partner',
				[
					'attribute' => 'logo_partner',
					'contentOptions' => function ($model, $key, $index, $column) {
						return ['class' => 'id-img'];
					},
					'content' => function ($data) use($dir) {
						return Html::img(Yii::$app->params['front-url'].$dir."/thumb/".$data['logo_partner'],['width'=>100]);
					}
				],
                'link_partner',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'options'=>['style'=>'width:200px'],
                    //'controller' => 'properties',
                    'template' => '{update}&nbsp;&nbsp;&nbsp;{delete}&nbsp;&nbsp;&nbsp;{report}',
                    'buttons' => [
                        'update' => function ($url,$data)  use ($event_id){
                            return '<a href="'.Url::toRoute(['update-partner', 'id' => $data['id'],'event_id'=>$event_id]).'"><span class="glyphicon glyphicon-pencil"></span></a>';
                        },
                        'delete' => function ($url,$data) use ($event_id){
                            return '<a href="'.Url::toRoute(['delete-partner', 'id' => $data['id'],'event_id'=>$event_id]).'"><span class="glyphicon glyphicon-trash"></span></a>';
                        },
                    ],
                ],
            ],
        ]); ?>
    </div>
</div>

backend/views/events/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Events */

$this->title = Yii::t('backend', 'Update Events: {nameAttribute}', [
    'nameAttribute' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Events'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="events-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories,
        'country' => $country
    ]) ?>

</div>